FROM centos:7

RUN yum install -y openssh-server sudo python3 passwd net-tools && \
    useradd ansible && \
    echo "ansible:ansible" | chpasswd && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir /var/run/sshd

EXPOSE 22

RUN ssh-keygen -A

CMD ["/usr/sbin/sshd", "-D"]